# Generated by Django 2.2 on 2019-04-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0002_remove_message_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_status',
            field=models.CharField(choices=[('r', 'R'), ('u', 'U')], max_length=1),
        ),
    ]
