# Generated by Django 2.2 on 2019-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0003_auto_20190419_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
