# Generated by Django 2.2 on 2019-04-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
