# Generated by Django 2.2 on 2019-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trash_status',
            field=models.CharField(choices=[('y', 'Y'), ('n', 'N')], default='N', max_length=1),
        ),
    ]
