# Generated by Django 2.2 on 2019-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0007_message_trash_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='trash_status',
        ),
        migrations.AddField(
            model_name='message',
            name='received_trash_status',
            field=models.CharField(choices=[('y', 'Y'), ('n', 'N')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_trash_status',
            field=models.CharField(choices=[('y', 'Y'), ('n', 'N')], default='N', max_length=1),
        ),
    ]
