# Generated by Django 2.2 on 2019-04-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AetherMail', '0008_auto_20190420_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
